### ISSUE TITLE
[BUG] JSONs are being double-encoded

### ISSUE THREAD

**Issue by tylerburleigh** [expfactory/expfactory#107]
When using the local filesystem, at least with the Stroop task, it seems JSONs are being double-encoded. 

Here's an example:

https://gist.github.com/tylerburleigh/43cb5a487c3e82d9df1f384e92b91ca7

I think the issue is that the AJAX POST is sending `data` as JSON:

```
$.ajax({
                         type: "POST",
                         url: '/save',
                         data: { "data": data },
                         success: function(){ document.location = "/next" },
                         dataType: "application/json",

                         // Endpoint not running, local save
                         error: function(err) {

                             if (err.status == 200){
                                 document.location = "/next";
                             } else {
                                 // If error, assue local save
                                 jsPsych.data.localSave('stroop_results.csv', 'csv');
                             }
                         }
                     });
```

And then `data` is being passed through the `write_json()` function by `filesystem.py`, which is encoding it a second time.

**Comment by vsoch** [comment]
This isn't a bug, whatever data the experiment sends **has** to be encoded into a json field. In the case that it were csv, for example, it would be single json encode with csv data as text. The solution is just to load and decide, and then (decode) the data value, whatever that might be. This means for json experiments, it would work to encode or not to encode from the server, and these happen to encode (as they should). There are some examples links in the docs that show how to read it, it's trivially one more line or two.

**Comment by vsoch** [comment]
https://gist.github.com/vsoch/76d8933e3ff7e080883362b8baa4a164

**Comment by tylerburleigh** [comment]
Alright, if that's the expected behavior.
It's not a big deal. I'm decoding it twice in R.

```
df <- fromJSON(my_file)
df <- fromJSON(df$data)
```

**Comment by vsoch** [comment]
That's right - imagine if the second index were csv, tsv, or xml - you would need to run a different command!
