### ISSUE TITLE
builder image needs to set psycopg2 version

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory#119]
There's an issue with latest psycopg2, the working version (from previous containers) is psycopg2==2.7.5

**Comment by earcanal** [comment]
Would it be possible to configure a CI task to do a regular (daily? weekly?) build of a test container to catch this kind of issue earlier in future?

**Comment by vsoch** [comment]
If you haven’t noticed, I’ve literally been working on this all day.
https://github.com/expfactory/expfactory/pull/120 :)

**Comment by earcanal** [comment]
Sorry, that was poorly worded (I had noticed - your usual prompt, above and beyond the call response - thanks :). It was just an idea that came to me that I wanted to capture/suggest before I forgot. Not even sure if it's feasible. Anyway, for _after_ the dust settles on your sterling work :)

**Comment by vsoch** [comment]
@earcanal I've made the CI test building the container, and packages are updated to be more specific versions. As for running this regularly - if expfactory v2 was used by a ton of people, regular testing would be warranted. However, it's not, and so it's more reasonable, resource wise, to have the builds done on demand. if you hit an issue, as you did this morning, you tell me and we fix it. The expfactory organization is also serving the version 1 of the software, and given testing of those experiments that are helping my previous lab, the limited time that we have for CI under this organization must go to that. I hope that you understand, and that reporting an issue as you did today is a reasonable approach.

**Comment by earcanal** [comment]
Np. I wasn't sure what resources were required/available. I might make a test build part of my workflow at the study _planning_ stage. It's been so quick and reliable to build containers now I have the hang of it, that I've tended to do this at the last minute. Not the best strategy on my part.

**Comment by vsoch** [comment]
Definitely a good idea! For this particular issue, if you had done a simple pip install of the right version of the psycog2 library (one from one of your working previous containers) before the setup.py install in your recipe, that would have fixed it too :) But it's much better you tell me, otherwise other users will hit it. I'm going to close this issue, since it's been fixed.
