### ISSUE TITLE
Raven's test version

### ISSUE THREAD

**Issue by mz973** [expfactory/expfactory#121]
## Version of Experiment Factory:

Hi,
I was looking to include a short version of Raven's test for my online study.  The Experiment Factory's version looks really good but I wonder which version of the Raven's matrices was it taken from (e.g. APM?) and are the items in the order of increasing difficulty?

Thanks!
Mengya 
### Expected behavior

Write here.

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

**Comment by vsoch** [comment]
hey @mz973 I think the best person to ask would be @IanEisenberg and @jkl071, both who coded / worked on the experiments. If it helps, the paper linked in the metadata is http://link.springer.com/chapter/10.1007/978-1-4615-0153-4_11 (maybe that answers your question!)
