### ISSUE TITLE
PsychoPy versions (of shift-task)?

### ISSUE THREAD

**Issue by jlhanson5** [expfactory/expfactory#122]
Hello, 

Our group was wondering if there might be PsychoPy versions of the tasks available? We were specifically looking to track down the shift-task. If anyone knows of relevant code, any help is deeply appreciated!

Thanks much,
Jamie.

**Comment by vsoch** [comment]
hey @jlhanson5  I think you'd do best to post here for that question https://github.com/psychopy/psychopy as expfactory doesn't generally provide psycopy tasks. Based on your use case with Pavlovia, you'd probably be good to go to use the psycopy task without expfactory. However, if you are interested in using expfactory with some psycopy task, I'd be happy to help figure out if the integration is possible. In summary, in that you want a psycopy task, I'd suggest engaging with that team, and bringing the task back here after the fact if integration with expfactory is desired. Let me know if you have any questions.
