### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/expfactory#132]
I noticed that [there are some high level vulnerabilities](https://quay.io/repository/vanessa/expfactory-builder/manifest/sha256:2cc60cd8cfc6c749a9bdade9a1b6828b9bd96a7f4f11499e50c3dd746c5dfb7c?tab=vulnerabilities) on the `latest` image. 

Is this cause for concern? I am about to submit a project proposal to a Research Ethics Board and felt like I should know what these vulnerabilities actually mean in terms of data security. Is it a matter of updating the packages?

**Comment by vsoch** [comment]
okay, I've pushed a test image, the same repository with tag `test-12-9-2020` (at the top) and it looks like the security scan is green! Do you want to take it for a spin to see if it works as you'd expect? If it looks good to you, I'll open a PR with the changes.

**Comment by vsoch** [comment]
Oops one second, I didn't build the image from the branch that is now for PR. Give me a second to build again!

**Comment by vsoch** [comment]
okay, all set.

**Comment by danieljwilson** [comment]
Great, have a meeting and will test afterwards!

**Comment by danieljwilson** [comment]
Seems like it worked (though keep in mind this is my second day using expfactory)...

**Comment by vsoch** [comment]
No worries! We have basic tests in the CI (and they have passed) and I'm of the opinion that it's better to release often, and we can address any issues that might arise.

**Comment by vsoch** [comment]
Issues fixed, closing issue.
