### ISSUE TITLE
No data is being saved if participants take longer than one hour for our task

### ISSUE THREAD

**Issue by SSchwoebel** [expfactory/expfactory#134]
## Version of Experiment Factory:

3.18

### Expected behavior

We have a self written experiment and want to save data.

### Actual behavior

If a participant takes longer than ~ an hour, no data is being saved, while if the participant is faster, data is being saved as expected.

### Steps to reproduce behavior

Our experiment is unfortunately not public yet.

I think there is a timeout occurring somewhere, so that data is not being saved. Unfortunately I couldn't find information about a timeout parameter in the documentation, so I'd like to ask if there is such a parameter and how to set it. If there is no such parameter, maybe you have an idea for a different solution (apart from splitting the task into shorter pieces)? Please let me know if there is any additional information I can supply.

Many thanks!

**Comment by vsoch** [comment]
There isn’t any limit on experiment length, the only reason I can think of so it wouldn’t be saved is if the request is too big. If you can’t give me something to reproduce then it’s much harder to debug. Have you tried adding a console.log to your experiment where it saves data, and even to views in the experiment container to nail down the actual bug? If you can give me a better sense of the true issue I can work with that to help. Thanks!

**Comment by paulsharpeY** [comment]
This triggers a vague memory of running into a problem with a large POSTs that I eventually resolved. I can't recall more than that right now. Can you grep git issues or your memory to see if there's a record @vsoch?

**Comment by vsoch** [comment]
I think this one? https://github.com/expfactory/expfactory/issues/77. @SSchwoebel would need to first see that the server is indicating that the payload is too large - I'd suggest this further debugging be the first step.

**Comment by paulsharpeY** [comment]
Yes. Maybe also check `client_max_body_size setting in `ngnix.conf`. Should be `20M` if built after #78.

**Comment by christianloeschen** [comment]
Being the one in charge for rolling out @SSchwoebel's tasks in production, I finally figured out the likely cause of this issue: Flask-WTFs CSRF token has a default lifetime of 3600s, or 1h [1]. After invalidation of the token, the ajax POST request will be rejected with a 400 status code [2], and clearly no results are stored anymore. Please find a very minimal task implemenation attached [3], that actually does nothing but storing results when clicked, until after 1h the CSRF token invalidates, error 400 returns and the task ends.

This issue may most likely be fixed either by adding an increased `WTF_CSRF_TIME_LIMIT` default in expfactory config, or making it configurable during deployment, depending on the tasks execution time.

Cheers

[1] https://flask-wtf.readthedocs.io/en/stable/config.html
[2] https://flask-wtf.readthedocs.io/en/stable/csrf.html
[3] [test_post.zip](https://github.com/expfactory/expfactory/files/5803735/test_post.zip)

**Comment by vsoch** [comment]
I'll open a PR to set the default to be 3 hours - I understand that setting the variable to None means the life of the session, but I think first we should try setting a longer period that should work for most use cases.

**Comment by vsoch** [comment]
Alright, please test https://github.com/expfactory/expfactory/pull/135 ! I made this testing repository a few years back that might be helpful https://github.com/expfactory/expfactory-testing.

**Comment by christianloeschen** [comment]
Confirmed, works like a charm! Thanks for your quick action!

**Comment by vsoch** [comment]
Great! Let's get it merged and released.

**Comment by vsoch** [comment]
Deployed to pypi: https://pypi.org/project/expfactory/3.19/
And builder containers to quay!: https://quay.io/repository/vanessa/expfactory-builder?tag=latest&tab=tags

**Comment by SSchwoebel** [comment]
Thank you @vsoch for the help and the quick resolution!
