### ISSUE TITLE
Pass token inside GET variable when in headless mode

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory#138]
This is not an issue but the wish for a new feature. 

It would be great to be able to pass the headless access token inside a GET variable. E.g. 

https://experiment.org/?token=35345-2314234-4535-34534

This way you can use external scripting for automatic tools, like testing that everything is working, etc.

**Comment by vsoch** [comment]
Thanks for opening this issue! I'll have this ready for you sometime tomorrow. I also might update the docs - I'm tired of that interface that isn't easy enough to navigate and search.

**Comment by vsoch** [comment]
okay @AlvaroAguilera it was pretty easy! I have a PR for you to test - instructions are in the description here: https://github.com/expfactory/expfactory/pull/139
