### ISSUE TITLE
Environment variable for the session timeout value 

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory#140]
Not an issue, but a feature request.

Currently the session timeout value is hardcoded in the file server.py:

`app.config["WTF_CSRF_TIME_LIMIT"] = xxx`

It would be great to use an environment variable for this, since we have some very long tests that we want to keep alive.

**Comment by vsoch** [comment]
okay here is a PR to test! https://github.com/expfactory/expfactory/pull/142

**Comment by vsoch** [comment]
You would add:
```
ENV EXPFACTORY_WTF_CSRF_TIME_LIMIT 99999
```
or similar in that container to define the wait time.
