### ISSUE TITLE
Saving data in experiment factory.

### ISSUE THREAD

**Issue by JuneOh710** [expfactory/expfactory#149]
I'm developing experiments to contribute to the Experiment Factory and I'm having trouble finding the best practice for saving data. I've coded a few experiments using jsPsych and also just JavaScript. I'm not sure how to send a POST request using jsPysch. Also, I'm not sure if my way of sending a POST request is acceptable. 

```
// how to save final result, I think:
async function sendResults(results) {
      function handleErrors(response) {
          if (!response.ok) {
              throw Error(response.statusText);
          }
          return response;
      }
      fetch("/save", {
          method: "POST",
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ data: results })
      })
          .then(handleErrors)
          .then(response => console.log("Request complete! response: ", response))
          .catch(error => console.log("We got an error: ", error));
}
```

**Comment by vsoch** [comment]
Can you not use one of the other experiments as an example? The expfactory server will handle saving based on your database setup. https://github.com/expactory-experiments

**Comment by JuneOh710** [comment]
I did look through a few examples and it looked like the jsPsych experiments use this function at the end of the experiment:
```
function assessPerformance() {
	var experiment_data = jsPsych.data.getTrialsOfType('single-stim-button')
	var missed_count = 0
	var trial_count = 0
	var rt_array = []
	var rt = 0
	for (var i = 0; i < experiment_data.length; i++) {
		rt = experiment_data[i].rt
		trial_count += 1
		if (rt == -1) {
			missed_count += 1
		} else {
			rt_array.push(rt)
		}
	}
	//calculate average rt
	var avg_rt = -1
	if (rt_array.length !== 0) {
		avg_rt = math.median(rt_array)
	} 
	var missed_percent = missed_count/experiment_data.length
  	credit_var = (missed_percent < 0.4 && avg_rt > 200)
	jsPsych.data.addDataToLastTrial({"credit_var": credit_var,
									"performance_var": performance_var})
}
```
I don't see how assessPerformance is sending a POST request to "/save".
Also, the non jsPysch experiments all use jQuery, which I'm avoiding to use to reduce the package size.

**Comment by vsoch** [comment]
Can you show me the experiment where you grabbed that? To answer your question, that does not look like a block that saves anything.

**Comment by JuneOh710** [comment]
I got it from this repo: https://github.com/expfactory-experiments/columbia-card-task-cold

However, I see that particular function called in many jsPsych experiments as the "on_finish" function.

**Comment by vsoch** [comment]
Yep that's correct! The snippet here (under on_finish) is what saves the data, and not the one you shared.
```javascript
$.ajax({
                         type: "POST",
                         url: '/save',
                         data: { "data": data },
                         success: function(){ document.location = "/next" },
                         dataType: "application/json",

                         // Endpoint not running, local save
                         error: function(err) {

                             if (err.status == 200){
                                 document.location = "/next";
                             } else {
                                 // If error, assue local save
                                 jsPsych.data.localSave('columbia-card-task-cold_results.csv', 'csv');
                             }
                         }
```

https://github.com/expfactory-experiments/columbia-card-task-cold/blob/e2a48342acd4d1bcc7b8f315aa115f92eb30fcc8/index.html#L49

**Comment by JuneOh710** [comment]
Thank you for the directions. I didn't realize the saving function would be in index.html. 
Is it safe to assume that using JavaScript fetch will yield the same results as jQuery ajax?

**Comment by vsoch** [comment]
Yes! And in fact we could update the experiments to use that. You just need to post to that endpoint.
