### ISSUE TITLE
/finish does not save the data

### ISSUE THREAD

**Issue by SaschaFroelich** [expfactory/expfactory#151]
Hi,

I have an experiment which I sometimes have to finish early, i.e. I have to skip all tasks in the queue after the first part is done.

I do this with the following command:

`window.location.href = '/finish';`

While this finishes the queue with no errors, it does not save the data of the first part. Is this intended? How could I make sure the data gets posted before termination?

Best,
Sascha

**Comment by vsoch** [comment]
Looks like I didn't see this! Did you get this figured out?

**Comment by SaschaFroelich** [comment]
Hi Vanessa, I have worked around it, so it's not really an issue anymore.
