### ISSUE TITLE
Minor documentation suggestion

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/expfactory#156]
Just noticed that I was getting an error running 

```bash
sudo apt-get install python-certbot-nginx
```
(from Step 2: Install certbot on [Generate an HTTPS Experiment Container](https://expfactory.github.io/generate-https))

The error is:
```bash
Package python-certbot-nginx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-certbot-nginx
```
And indeed running the following fixed it for me:
```bash
sudo apt-get install python3-certbot-nginx
```

**Comment by vsoch** [comment]
All set, thank you! https://github.com/expfactory/expfactory.github.io/commit/869079ca373f26cd0974dc573721e13520afa6b2
