### ISSUE TITLE
Issue running headless

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/expfactory#157]
## Version of Experiment Factory:

Latest

### Expected behavior

I am following the [Generate an HTTPS Experiment Container](https://expfactory.github.io/generate-https) and at the last step we are given code to run the docker container headless. 

This works when I run the first snippet of code given:

```bash
docker run -d -p 80:80 -p 443:443 \
           -v /etc/ssl/certs:/etc/ssl/certs:ro \
           -v /etc/ssl/private:/etc/ssl/private:ro \
           expfactory/experiments start
```
This seemed to work find. I could see the container running when typing in `docker ps` and I was able to access the experiments through my https URL.

Then I tried to run the next code which is supposed to:

> bind the data location in the container to your host, so that if the container stops and goes away, the data persists.

However, when I do this it doesn't seem to work.

### Actual behavior

When I run (note that I added what I think is a missing backslash after `scif`:

```bash
docker run -d -p 80:80 -p 443:443 \
           -v /etc/ssl/certs:/etc/ssl/certs:ro \
           -v /etc/ssl/private:/etc/ssl/private:ro \
           -v $PWD:/scif
           expfactory/experiments start
```

It spits out an identifier code but when I try running `docker ps` there doesn't appear to be anything actually running, and I can no longer access the experiments on my URL.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/7377893/157211786-40cda647-6954-4bca-8ede-0db402d0e6dd.png">

Also, on a side note, what is `scif`? Is this where data is supposed to be stored? Not in the `data` folder? Sorry if this should be obvious...

### Steps to reproduce behavior

I guess just run the code?

**Comment by vsoch** [comment]
> It spits out an identifier code but when I try running docker ps there doesn't appear to be anything actually running, and I can no longer access the experiments on my URL.

That does seem buggy1 Here is what you can do. Run the first command that you know to be working, and then shell into your container to look around, and look for the data. Then run the second command again with a mode educated (we hope) bind. I suspect the addition of binding the $PWD to data is messing something up, e.g., binding away the experiments that are supposed to be there (oops).

> Also, on a side note, what is scif? Is this where data is supposed to be stored? Not in the data folder? Sorry if this should be obvious...

scif stands for the scientific filesystem. https://academic.oup.com/gigascience/article/7/5/giy023/4931737. It was a vision for an entire specification and tooling for how to organize data in containers.

**Comment by danieljwilson** [comment]
Um, so I think I figured this out - 

I think the issue was that the code provided:

```bash
docker run -d -p 80:80 -p 443:443 \
           -v /etc/ssl/certs:/etc/ssl/certs:ro \
           -v /etc/ssl/private:/etc/ssl/private:ro \
           -v $PWD:/scif
           expfactory/experiments start
```
is not just missing a `\`, but in fact the line:
```bash
-v $PWD:/scif
```
should be:
```bash
-v $PWD:/scif/data \
```

**Comment by danieljwilson** [comment]
Apologies for making an issue before digging more but I was pretty stuck for a couple of hours 🤦

**Comment by vsoch** [comment]
No need to apologize! I'm sorry my typo caused you this frustration. Do you want to PR to the docs to fix it? Should be at the bottom of here: https://github.com/expfactory/expfactory.github.io/blob/master/pages/1-generate-https.md

**Comment by danieljwilson** [comment]
👍
