### ISSUE TITLE
Hiding task/survey name in browser?

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/expfactory#163]
## Version of Experiment Factory:

3.2.13

### Expected behavior

Would be in some cases nice if participants were not cued as to the task or survey they were doing by the name in the URL...not critical but if possible could be nice 🙂 

### Actual behavior

URL ends with name of task.

### Steps to reproduce behavior

n/a

**Comment by earcanal** [comment]
A workaround is to hide the URL by [runing your experiments fullscreen](https://github.com/expfactory-experiments/breath-counting-task/blob/master/index.html).

**Comment by danieljwilson** [comment]
Thanks @earcanal, will look into that!

**Comment by vsoch** [comment]
The titles are part of the static html, so I'm not sure how we would feasibly do this - even removing the title element:

```
document.getElementsByTagName('title')[0].remove()
```
I think most browsers will already have read and loaded it! I second what @earcanal said - probably just fullscreen is your best bet.

**Comment by danieljwilson** [comment]
Okay sounds good...will aim for the fullscreen option 🙂

**Comment by danieljwilson** [comment]
> A workaround is to hide the URL by [runing your experiments fullscreen](https://github.com/expfactory-experiments/breath-counting-task/blob/master/index.html).

@earcanal this code doesn't seem to be working for me - I am wondering if it is designed for the jspsych experiments instead of the surveys? I tried a few things I found online but nothing seemed to work (granted my JS skills are basically nonexistent)...

**Comment by earcanal** [comment]
Yes, this is for an experiment. Is there an option to tell [the survey generator](https://github.com/expfactory/survey-generator) to run fullscreen @vsoch?

**Comment by vsoch** [comment]
You'd need / want to add it to be done via javascript, e.g., https://www.w3schools.com/howto/howto_js_fullscreen.asp and then what we probably really need is a survey builder action that we can add to each survey repo, and then just trigger a dispatch event to trigger with fullscreen. But then we run into trouble given that a particular participant doesn't want fullscreen.

Another strategy would be to make a starting experiment or block that engages full screen, and then the rest will use it. That might be more logical for customizing a specific battery.

**Comment by danieljwilson** [comment]
Okay got it - this isn't completely critical atm, but I like your suggested workaround @vsoch ...

**Comment by earcanal** [comment]
Yeah, a "config" experiment might be nice, with features exposed via `QUERY_STRING`. Relatively easy to add features for someone with some js, and then easily configured by someone without. You could also drop that into different stages within a battery if you wanted to twiddle switches.

**Comment by danieljwilson** [comment]
Just for the record - I tried the workaround (made the battery start with an experiment using the new branch you created @vsoch ) but it actually went out of fullscreen as soon as I completed the experiment (even though I was going into another experiment next)...

Definitely not the end of the world but I think the minor concern is just that if you let subjects see what the tests and surveys are called (and survey's in particular) that you may potentially slightly bias responses...

**Comment by vsoch** [comment]
I'd also argue (having taken a lot of these) that it's pretty easy to figure out from the questions alone :P

**Comment by danieljwilson** [comment]
Fair! 😆

**Comment by vsoch** [comment]
Did you get this figured out?

**Comment by danieljwilson** [comment]
Not really - just kind of relying on two not crazy assumptions that:
1. Most people won't look at the title in the URL
2. If they do it isn't really going to affect their answers/performance

If I had the option of masking the names I would choose it, but I think that any effect would be null or close to null

**Comment by vsoch** [comment]
The experiments are served entirely statically, which means we'd require an option that says "install these into random UUID names" and then we would have to turn of UUID validation: https://github.com/expfactory/expfactory/blob/ff2c5cd46fe702f3371b44edec4b27919184f1fa/expfactory/validator/experiments.py#L141-L147. I guess I'm not convinced the names are even as revealing as the questions themselves. And then anyone using your container wouldn't have the option to undo that. If you are saying there is little to no effect I'm leaning towards saying we don't need this, at least until there is work to show it's important to do?

**Comment by danieljwilson** [comment]
I agree. I would put this at lowest of priority and/or just close it.

**Comment by vsoch** [comment]
@danieljwilson I think there could be a way! I promise I will try soon.

**Comment by danieljwilson** [comment]
Oh wow, nice!

**Comment by vsoch** [comment]
hey @danieljwilson - I have a prototype ready for you to test! https://github.com/expfactory/expfactory/pull/168 If we can review and merge that, after the work is done there I'll work on #166 (checking for experiment results on server load).

This was tricky but I'm glad we tried it out (and I hope it works after your testing!) because indeed it's a nicer design to not obviously show the name, even if it's only briefly with fullscreen. And hey, if we get this merged you could run "the same" randomized experiments with/without the name and see if it actually makes a difference.

For testing, you should be able to easily build this dockerfile (and customize the experiments installed to your liking) https://github.com/expfactory/expfactory/blob/24224a35e5248f5d6d491ef982d57624e834e25e/examples/docker/hidden-names-container/Dockerfile. You can remove `ENV EXPFACTORY_CONCEAL_NAMES=true` to get the original version (without conceal) to test. I tested with/without for the portal entrypoint (not headless) and only for one experiment.

**Comment by danieljwilson** [comment]
Okay, great, thank you! 🙏

I will hold off on running this in my current experiment but will test it out and include it in the next round (which is in a couple of week).

And that would be amazing if you were able to figure out #166 as I am currently pausing an ongoing experiment while I (and by I, I mean me asking you 😬...) try and figure out a solution 😅

**Comment by vsoch** [comment]
Yep, I'm doing my best! See #169 for a quick fix for your current issue - I can't test easily so I'll need your help to do that - e.g., build some testing container using the branch (a Dockerfile in the examples folder and change the branch to the PR branch, or even use your Dockerfile) and then copying your previous data over, and trying out the new container to see if it loads previous experiments (and if not look in the log and see what it is reporting for finished experiments, or otherwise a bug!)

**Comment by danieljwilson** [comment]
👍

**Comment by vsoch** [comment]
hey @danieljwilson did you get a chance to test things out? Could you let me know if you won't be able to? If not, I'm just going to merge with my testing, and people can open issues if any new ones arise.

**Comment by danieljwilson** [comment]
Hi @vsoch , I am actually just starting the process of doing so right now - sorry for the delay - I have been traveling (France/London and now am on a stopover in Montreal) so have had limited access the last few days. And wifi here is verrrry slow...but basically have from now until my flight in 2 hours to test things out. I'll keep you posted.

**Comment by vsoch** [comment]
Wow! I pretty much exist in the few mile radius I run around my apartment... major props to you world traveler! :airplane:

**Comment by danieljwilson** [comment]
This is a bit outside the norm but had a couple big family events...

On another note I am getting a bit stuck and realizing that I wish I was a bit more fluent/capable in terms of helping with the debugging. I don't think I am going to be able to finish before the flight. 

My original plan was just to create a new minimal version of the experiment on my virtual server
<img width="579" alt="image" src="https://user-images.githubusercontent.com/7377893/193430761-7dbc59d8-699a-41c4-a703-4bf682557034.png">

But then I am worried that if I run it it may interfere with my other (currently running) container? I'm going back to the https documentation since I didn't understand if I have to have another URL that is associated with this testing version -

But then I thought that perhaps it makes more sense just to be testing this locally so now I am trying that...

**Comment by vsoch** [comment]
Yes you definitely want to be testing locally!

With docker, although the web server might run on port 80 inside the container, you can map that to any port on your development machine. E.g, if normally you'd do:

```bash
$ docker run -p 80:80 -it experiment start
```

You could just as easily do:

```bash
$ docker run -p 5050:80 -it experiment start
```
to map port 80 in the container to 5050 on your host (or any port you desire).

**Comment by danieljwilson** [comment]
Okay, trying locally now :)

**Comment by vsoch** [comment]
The Dockerfile will need to install expfactory from the branch you are testing - if you use #169 it should have both the hidden argument option and the ability to check data state.

**Comment by danieljwilson** [comment]
Yes, I did that part I believe, using:

`RUN git clone -b add/check-data-exists https://github.com/expfactory/expfactory`

It works but I am trying to figure out how to see where the data is being stored - right now I am shelling into the container and can see the "users" but I am trying to figure out how to access the user file folders so that I can put some completed experiments in them and test - but then also not how to match the names I input the the GUI to the identifiers that are in `/scif/data`

This is probably in the documentation, but they are boarding the flight now and I am on kid duty all day tomorrow so probably can't get back on this until tomorrow night...

**Comment by vsoch** [comment]
No worries! Yes the data should be under /scif/data/expfactory and the experiments are under the same in /scif/apps. To be very redundant, to test adding the hidden URLs you'll need to build with the environment variable for it set in the Dockerfile, and testing completed data should be easier (just look to see what is there and then ensure you don't repeat). I think for the demo I made (in examples/docker) I made sure that one person was finished, and the other still had one to do.

Have a good flight!

**Comment by danieljwilson** [comment]
Hey so I just ran through my battery debugging time window without a huge amount of success.

I think the confusion for me is managing users and then putting completed files in their folders to test against...

Even creating users is problematic as for some reason they are not being recognized...i both just created a folder and then also used the `docker exec <container> expfactory users --new 3` command to create user tokens, and they seem to "exist"

```shell
root@da857fed4c20:/scif/data/expfactory# ls
352b77ab-4d31-49f2-a577-720e6892a597  70981253-ad63-4195-abac-05c4bec635ec
6281277a-8f27-46f0-a76c-06b151f74207  djw_testing
```

But when I try to use them I am getting an error:
![image](https://user-images.githubusercontent.com/7377893/193642259-8fc608b3-4636-4d97-a5f4-27076f053c72.png)

Basically my plan was to:
- build minimal container (say 4 experiments, so not totally minimal)
- create a couple subject/tokens
- complete an experiment or two with one of the subjects
- stop and remove the container
- rebuild a slightly different container (e.g. with only 3 of the 4 previous experiments)
- start the container while maintaining the same subjects with their associated data files from the previous container
- test to see if it is serving experiments that have already been completed
- test that once the un-finished tasks are done it completes the subject

For the moment I am letting subjects know that when they are only getting repeatedly served the 2 broken experiments that they are done...but this is a pretty clonky (and annoying for them) way of doing things. I will be running this again in December so I will definitely have more time to spend on it before then but this week I have an end of week presentation so am feeling the time crunch (just to say that if I don't make more progress on this it is not due to lack of interest).

**Comment by vsoch** [comment]
hmm yeah I've had that bug too! I think it might have been a permissions error on the folders - e.g., if they are under the wrong ownership the container can't easily read/see them so they are reported to not exist.

**Comment by vsoch** [comment]
This is now merged.
