### ISSUE TITLE
Check available results before starting test (Feature request)

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory#170]
Imagine the following use case (which is not entirely unlike ours): you have 10 tests running on an instance and they take 3 hours to complete. The participant completes the first 8 of them and then the browser crashes, he/she has to leave for work or what not causing the cookie to time out or be lost. 

Even though the result files are stored for the first 8 tests, the poor guy has to start again from the beginning when he decides to resume the experiment. 

It would be awesome to check for result files after entering the token and skip those tests. This would reduce the number of curse words detected by Alexa in Germany by 20%.

**Comment by vsoch** [comment]
I just implemented this! https://github.com/expfactory/expfactory/pull/169. It does need reviewers :)

you should be able to build the newly added Dockerfile in examples/Docker to build a container using the PR branch and test it out.

**Comment by AlvaroAguilera** [comment]
This is awesome and seems to be working fine. Thank you!
