### ISSUE TITLE
mysql data field too small, data lost?

### ISSUE THREAD

**Issue by tfeige91** [expfactory/expfactory#175]
## Version of Experiment Factory:

Hi Vanessa,
I experienced when using a mysql database for storing experiment data, the data field was formatted as text, which was too small for me so I changed it manually to long-text. However in one test battery I forgot it and the data was truncated. Is there any chance to find this data in some log-files or so?

Thanks for your help!

**Comment by vsoch** [comment]
I don't think so - I'm sorry about your data loss.

**Comment by tfeige91** [comment]
Saving failed in that test battery and it would not move to the next test (which I understood just today...). There is no chance it saved csv files somewhere in the container instead, is there?

**Comment by vsoch** [comment]
If you are saving data to a database proper, there shouldn't be any saving of text files. The logs for the container would only have a line that says they are taking / completing an experiment.

**Comment by tfeige91** [comment]
Thanks for your help anyways!

**Comment by tfeige91** [comment]
I got pretty close to securing the data actually: In the expfactory.log the failed queries are being logged but unfortunately they are truncated :) Might there be any other place that might have logged the queries?

**Comment by vsoch** [comment]
@tfeige91 I don't have any new information for you.

**Comment by tfeige91** [comment]
All right :)
