### ISSUE TITLE
TLA fail

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#27]
What are the acronyms `PHI` and `IRB` in [this context](https://expfactory.github.io/expfactory/usage)?

**Comment by vsoch** [comment]
PHI refers to "personal health information" as determined by HIPAA and it's generally any kind of information that can identify a person. Here is Stanford's definition: https://humansubjects.stanford.edu/research/documents/hipaa.pdf

IRB is an institutional review board - before you do a study (and collect data) you write up your plan, and they have to approve it before moving forward.

So in that context, it is saying you would have written up that you were using the Expfactory tool, and added details about how you planned to keep track of people without violation of any rules set by HIPAA, etc. It's standard part of doing a research study that involves humans that the protocol needs to be approved first.

**Comment by earcanal** [comment]
So maybe write that but point out that it's US-specific and you'll have your own national/institutional ethical guidelines?

**Comment by vsoch** [comment]
oh haha, I didn't even realize this :) Yes if you want to suggest a change (based on what you know and I do not!) I would appreciate the help!
