### ISSUE TITLE
Port number not preserved by experiment UI

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#34]
Assumption: Port 80 is already bound, so you need to map a different host port.  This will be common if you have a host that already runs a web server.  So

    $ docker run -p 8080:80 vanessa/expfactory-experiments start

Reproduce:

1. http://some.host:8080/
1. Tick **test-task**
1. Click **Proceed**
1. Click **Submit**

URL opened is `http://some.host/start` rather than `http://some.host:8080/start`.

**Comment by vsoch** [comment]
Hey @earcanal! I wouldn't call this an issue, port 80 is going to work and be best in most cases so I'm reluctant to change it.

**Comment by vsoch** [comment]
And in fact it's baked into the web server provided by the image, and changing it would be complicated. If you are using port 80 on your host you can stop the server and restart when done, or if you have another docker image you could do the same.

**Comment by earcanal** [comment]
It foils my cunning plan to deploy to a vm which I have access to, as I'm not allowed to suspend Apache which owns port 80 on that host. :(

**Comment by vsoch** [comment]
But you are allowed to use other ports?

**Comment by vsoch** [comment]
You would need to change the port in nginx.conf, and the docker-compose.yml and (maybe?) the Dockerfile. The experiments are not currently designed to be hosted via a port so you may run into issues there. It's still worth a try!

**Comment by earcanal** [comment]
No worries.  I just wanted to document this issue.  I think it's telling me to find a different Docker host ;-)  BTW, I'm starting to get the hang of this now.  I have a Docker hub account and everything!

**Comment by vsoch** [comment]
woohoo!

I'm not sure if it's a good fit, but I've been using heroku for small deployments (and it's free). You probably would need to look into how they manage data and databases and make sure it's secure, etc, but it's a good option.

**Comment by earcanal** [comment]
Hmm, just when I've got my head around Docker?!!  How can you find out how big your container(s) are, so you can match them to a host (e.g. https://www.digitalocean.com/products/one-click-apps/docker/)?

**Comment by vsoch** [comment]
A docker image is just a list of layers, so your best bet is get the manifest and look at the sizes. You can also just shell into your image and use whatever du/command line tool you prefer to estimate size.

**Comment by vsoch** [comment]
Try

```
docker inspect postgres | grep Size
```
that number looks like bytes (you should double check this) so convert to your type of choice.

**Comment by vsoch** [comment]
@earcanal any progress here?

**Comment by earcanal** [comment]
I just used `du` inside the container.
