### ISSUE TITLE
Can't specify task and survey order

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#35]
There's currently no way to specify the order in which tasks (and surveys) are run.  This is a common requirement (at least in the studies I've run!).

I think the order is currently random, so as a tiny first step, the UI could indicate this in big letters at the task-ticking stage.

**Comment by vsoch** [comment]
yes this is very important! I might have some time tomorrow or later today to do this - could you give me a list of commonly wanted ordering algorithms so I can add them all?

**Comment by earcanal** [comment]
The only ordering 'algorithm' I currently require is `user-defined`, and I think I'd like to be able to do this outside of any UI (json? yaml?).  This is making me think through the `test remote participant` use case in terms of their (and my) UX (cf. #2).  Should I propose something for this under a different issue?

**Comment by vsoch** [comment]
heyo! Just a heads up that I started working on this today, but ran out of steam. The trigger to randomize / not is done, but I need to figure out how to respect some ordering chosen by the user using jquery. I have a few ideas I think I can try out.

**Comment by vsoch** [comment]
I think we can tackle the question here - we could do a specification at runtime, and at buildtime, to have a "hard coded" order. I'll wrap this issue into the two others I'm working on for you now.

**Comment by vsoch** [comment]
okay - just reproduced the sqlite3 error - it's just an index error and an easy fix!

**Comment by vsoch** [comment]
okay sqlite3 is fixed, working on the ordering now.

**Comment by vsoch** [comment]
okay ordering ready for testing! https://github.com/expfactory/expfactory/pull/38

**Comment by vsoch** [comment]
done
