### ISSUE TITLE
Surveys incompatible with --database sqlite

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#36]
Reproduce:

With an image containing a survey (e.g. **state-mindfulness-survey**):

`docker run -v /tmp/test/data:/scif/data -d -p 80:80 earcanal/test --database sqlite start`

1. Run (for example) **state-mindfulness-survey** and **test-task**

If survey is run first (depends on randomisation) it ends with a `Download` button and the json is downloaded rather than written to the sqlite database.  The battery is then blocked.  I haven't observed behaviour when **test-task** is run first.

**Comment by vsoch** [comment]
hey earcanal you can test using these recipes https://github.com/expfactory/expfactory/pull/38 to see if the sqlite error is resolved.

**Comment by vsoch** [comment]
fixed
