### ISSUE TITLE
create new version of experiment testing robot

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory#37]
We can get through a substantial number of the testing given that jspsych is used, see https://github.com/expfactory-experiments/stroop/issues/2 @earcanal feel free to put your thoughts here!

**Comment by earcanal** [comment]
A project in its own right really, but I would go for:

1. Whatever testing framework can at least report run time errors
2. Something along the lines of Selenium that will do user-level test coverage

**Comment by vsoch** [comment]
yep, that's exactly how I did it! I should be able to re-implement that pretty easily. although I'd like to do it better. I'll ping you here when I have something to test out!

**Comment by vsoch** [comment]
This should currently be done for:
 - jspsych
 - surveys

**Comment by vsoch** [comment]
I think I did this!
