### ISSUE TITLE
generate headless start

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory#39]
per our discussion (@earcanal ) we would want to be able to start a container that:
 - has a pre-determined ordering
 - is "headless" in that it doesn't start a user at the portal entry
 - can generate and then serve custom (token protected?) urls (and then logically the experimenter should be able to edit / generate more if needed)

**Comment by vsoch** [comment]
@earcanal would an entry page that requires the user to put in the token be suitable? That way we don't need to have people's browser history store the token, and if they pause and return to the experiment, it will find (or not find) the token in the session.

**Comment by earcanal** [comment]
Yes.

**Comment by earcanal** [comment]
Do I still need `Dockerfile` and `startscript.sh` from the gist in #38?  I can't connect to localhost after

    docker run -v $PWD:/data vanessa/expfactory-builder build test-task state-mindfulness-survey
    docker build --no-cache -t earcanal/study3 .
    docker run -v $PWD/data:/scif/data -d -p 80:80 earcanal/study3 --experiments test-task,state-mindfulness-survey --database sqlite start

After building using gist from #38, this starts a container

    docker run -v $PWD/data:/scif/data -d -p 80:80 earcanal/study3 start

but these don't

    docker run -v $PWD/data:/scif/data -d -p 80:80 earcanal/study3 --experiments test-task,state-mindfulness-survey --database sqlite start
    docker run -v $PWD/data:/scif/data -d -p 80:80 earcanal/study3 --experiments test-task,state-mindfulness-survey start

Was hoping to give a demo of the headless ordering noon UK tomorrow ;-/

**Comment by vsoch** [comment]
The gist shouldn't be needed anymore - the vanessa/expfactory-builder on Docker Hub is updated, so you should be able to generate a Dockerfile and startscript.sh from that. Did you try that?

**Comment by vsoch** [comment]
I'm still working on the headless, it's almost done but it won't be done by noon tomorrow. I think you can show the ordering, and then there are some screenshots of the work in progress. https://github.com/expfactory/expfactory/blob/headless/docs/pages/2-usage.md#start-a-headless-experiment-container

**Comment by earcanal** [comment]
Thanks, I'd forgotten to ` docker pull vanessa/expfactory-builder`

I still get the UI on port 80 after `docker run -v $PWD/data:/scif/data -d -p 80:80 earcanal/study3 --experiments test-task,state-mindfulness-survey --database sqlite start`.

Is that expected behaviour?  I thought when I last tested that `--experiments` avoided experiment selection UI.

BTW, headless docs are ideal for talk today.  Thanks. :)

**Comment by vsoch** [comment]
I don't know what you tested (maybe your memory is tricking you because we talked about it?) but the behavior you are looking for is a headless start (avoiding selection with the UI) and that's what I'm working on now.

**Comment by earcanal** [comment]
I thought I saw that behaviour in my UAT, but it could be a false memory, wishful thinking etc!

**Comment by vsoch** [comment]
Done with #41
