### ISSUE TITLE
Report container startup errors in shell

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#43]
Is there a way to tell the user why something like this failed?

`docker run -v /tmp/test/data:/scif/data -d -p 80:80 expfactory/experiments --study id test --database sqlite start`

The error isn't captured anywhere and all you can do is `docker ps` to see that the container isn't running.

**Comment by vsoch** [comment]
The mistake is that `--study id` is two words, so the id is being chomped to be used for the id, then the rest of the argument parsing goes wanky. This is more appropriate for the user for post an issue here and for others to help him/her to see the mistake.

**Comment by earcanal** [comment]
I know what the issue is *in this case*, but this is a *class* of errors i.e. no feedback for *any* syntax error.  I think this isn't resolved yet.

**Comment by vsoch** [comment]
hey @earcanal let me move the builder to it's own respective repo, and then we can discuss there.
