### ISSUE TITLE
Can reuse token after finishing [filesystem]

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#47]
Moving out of #41.

@vsoch "As long as a partiicpant isn't finished, you would be able to re-use (imagine you are a participant that starts a battery and comes back later). Was this after finishing, and did you see a status of finished?"

**Comment by earcanal** [comment]
Yes, this was after finishing.

    docker run -p 80:80 -d --name foo -v /tmp/test/data:/scif/data expfactory/experiments --headless --experiments test-task,state-mindfulness-survey --no-randomize start

I used  token `0d1d1886-c2c5-46d1-829f-5712684852ed`

Before first completion

`    root@02edbb8d5cb8:/scif/apps# expfactory users --list
    /scif/data/expfactory/0d1d1886-c2c5-46d1-829f-5712684852ed	0d1d1886-c2c5-46d1-829f-5712684852ed[active]
    /scif/data/expfactory/285d4f50-f5ba-47d4-bb68-137cd0eea5e6	285d4f50-f5ba-47d4-bb68-137cd0eea5e6[active]
    /scif/data/expfactory/31f78d8a-a3b8-4c35-936e-ecf34a7623c6	31f78d8a-a3b8-4c35-936e-ecf34a7623c6[active]
    /scif/data/expfactory/4a78e1ae-4f46-47de-9a59-b23be28a9ec4	4a78e1ae-4f46-47de-9a59-b23be28a9ec4[active]
    /scif/data/expfactory/5ec4ebb0-fd06-4861-922f-59ecc5e16d9a	5ec4ebb0-fd06-4861-922f-59ecc5e16d9a[active]
    /scif/data/expfactory/7cd74cb3-6b44-4e36-9be2-473379f9d636	7cd74cb3-6b44-4e36-9be2-473379f9d636[active]
    /scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d_revoked	8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d[revoked]`

After first completion

`    root@02edbb8d5cb8:/scif/apps# expfactory users --list
    /scif/data/expfactory/0d1d1886-c2c5-46d1-829f-5712684852ed	0d1d1886-c2c5-46d1-829f-5712684852ed[active]
    /scif/data/expfactory/285d4f50-f5ba-47d4-bb68-137cd0eea5e6	285d4f50-f5ba-47d4-bb68-137cd0eea5e6[active]
    /scif/data/expfactory/31f78d8a-a3b8-4c35-936e-ecf34a7623c6	31f78d8a-a3b8-4c35-936e-ecf34a7623c6[active]
     /scif/data/expfactory/4a78e1ae-4f46-47de-9a59-b23be28a9ec4	4a78e1ae-4f46-47de-9a59-b23be28a9ec4[active]
    /scif/data/expfactory/5ec4ebb0-fd06-4861-922f-59ecc5e16d9a	5ec4ebb0-fd06-4861-922f-59ecc5e16d9a[active]
    /scif/data/expfactory/7cd74cb3-6b44-4e36-9be2-473379f9d636	7cd74cb3-6b44-4e36-9be2-473379f9d636[active]
    /scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d_revoked	8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d[revoked]`

**#FAIL** After *second* completion reusing `0d1d1886-c2c5-46d1-829f-5712684852ed`

`root@02edbb8d5cb8:/scif/apps# expfactory users --list
/scif/data/expfactory/0d1d1886-c2c5-46d1-829f-5712684852ed	0d1d1886-c2c5-46d1-829f-5712684852ed[active]
/scif/data/expfactory/285d4f50-f5ba-47d4-bb68-137cd0eea5e6	285d4f50-f5ba-47d4-bb68-137cd0eea5e6[active]
/scif/data/expfactory/31f78d8a-a3b8-4c35-936e-ecf34a7623c6	31f78d8a-a3b8-4c35-936e-ecf34a7623c6[active]
/scif/data/expfactory/4a78e1ae-4f46-47de-9a59-b23be28a9ec4	4a78e1ae-4f46-47de-9a59-b23be28a9ec4[active]
/scif/data/expfactory/5ec4ebb0-fd06-4861-922f-59ecc5e16d9a	5ec4ebb0-fd06-4861-922f-59ecc5e16d9a[active]
/scif/data/expfactory/7cd74cb3-6b44-4e36-9be2-473379f9d636	7cd74cb3-6b44-4e36-9be2-473379f9d636[active]
/scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d_revoked	8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d[revoked]`

You can see the overwriting happening on the local fs:

    $ ls -l 0d1d1886-c2c5-46d1-829f-5712684852ed
    total 12
    -rw-r--r-- 1 root root 4999 Dec 11 16:40 state-mindfulness-survey-results.json
    -rw-r--r-- 1 root root 2326 Dec 11 16:42 test-task-results.json
    $ ls -l 0d1d1886-c2c5-46d1-829f-5712684852ed
    total 12
    -rw-r--r-- 1 root root 4999 Dec 11 16:42 state-mindfulness-survey-results.json
    -rw-r--r-- 1 root root 2326 Dec 11 16:42 test-task-results.json

**Comment by vsoch** [comment]
What container is expfactory/experiments? I have not updated that container for this PR. Did you build it yourself?

**Comment by vsoch** [comment]
Ah I think I found it... here?

```
docker run -v /tmp/data:/data vanessa/expfactory-builder-dev build test-task tower-of-london breath-counting-task state-mindfulness-survey
docker build -t expfactory/experiments .
```

**Comment by vsoch** [comment]
One quick comment (I'm building the image again now) when you are testing / generally using docker build, it's important to not let it use the cache, e.g.

```
docker build --no-cache -t expfactory/experiments .
```
Otherwise, if you do something like download from a repo (and the line is the same but the repo is changed) you will use the cached version and not know it! I've run into so many issues this way!

Okay testing now!

**Comment by vsoch** [comment]
okay here are my complete steps:

Build
```
$ docker run -v /tmp/data:/data vanessa/expfactory-builder-dev build test-task tower-of-london breath-counting-task state-mindfulness-survey
docker build --no-cache -t expfactory/experiments .
```
Run in headless mode
```
$ docker run -p 80:80 -d --name foo -v /tmp/test/data:/scif/data expfactory/experiments --headless --experiments test-task,state-mindfulness-survey --no-randomize start
b8d10244d74136d604f3905082282d19f75e35978474214d1ae01ab25ae206e4
```
Confirm that there are no users

```
$ docker exec foo expfactory users --list
```

Create a user
```
$ docker exec foo expfactory users --new 1
DATABASE	TOKEN
/scif/data/expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83	e1f837a9-1b3a-4d94-9516-a7d7fd199e83[active]
```
List the user (same as above)

```
docker exec foo expfactory users --list
/scif/data/expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83	e1f837a9-1b3a-4d94-9516-a7d7fd199e83[active]
```
(Do experiments in browser now until I see finished screen)

List again - still not finished
```
docker exec foo expfactory users --list
/scif/data/expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83	e1f837a9-1b3a-4d94-9516-a7d7fd199e83[active]
```

But ah-ha! I think I know the bug. When we created the container, we installed four experiments (test-task tower-of-london breath-counting-task state-mindfulness-survey) but running it above we only use two (test-task,state-mindfulness-survey) so I think it must be that we are making the wrong comparison somewhere. Let me dig into the code a bit and figure this out - need to go afk for a few minutes first.

**Comment by vsoch** [comment]
okay here is the bug - the complete subid is being stored with the folder name (subid) and then I'm (redundantly) adding it again, so the weird folder name is not found on the file system:

```
docker exec foo expfactory logs

Logged in user [subid] expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83
Next experiment is test-task
[router] None --> test-task for [subid] expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83 [username] None
Redirecting to /experiments/test-task
Rendering experiments/experiment.html
Saving data for test-task
Finishing test-task
Finished test-task, 1 remaining.
Next experiment is state-mindfulness-survey
[router] test-task --> state-mindfulness-survey for [subid] expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83 [username] None
Redirecting to /experiments/state-mindfulness-survey
Rendering experiments/experiment.html
Saving data for state-mindfulness-survey
Finishing state-mindfulness-survey
Finished state-mindfulness-survey, 0 remaining.
/scif/data/expfactory/expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83 does not exist, cannot finish. expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83
/scif/data/expfactory does not exist, cannot finish. expfactory/e1f837a9-1b3a-4d94-9516-a7d7fd199e83
```

**Comment by vsoch** [comment]
woo I think this is fix! I rebuilt / did the experiments as noted above

then looked at the logs:
```
docker exec foo expfactory logs
Logged in user [subid] expfactory/3eb83c14-ee01-4b38-a579-c927942732a8
Next experiment is test-task
[router] None --> test-task for [subid] expfactory/3eb83c14-ee01-4b38-a579-c927942732a8 [username] None
Redirecting to /experiments/test-task
Rendering experiments/experiment.html
Saving data for test-task
Finishing test-task
Finished test-task, 1 remaining.
Next experiment is state-mindfulness-survey
[router] test-task --> state-mindfulness-survey for [subid] expfactory/3eb83c14-ee01-4b38-a579-c927942732a8 [username] None
Redirecting to /experiments/state-mindfulness-survey
Rendering experiments/experiment.html
Saving data for state-mindfulness-survey
Finishing state-mindfulness-survey
Finished state-mindfulness-survey, 0 remaining.
Expfactory Version: 3.1
```
Note there is no error/warning about not being able to save. I can now look at the list to confirm I'm finished:

```
$ docker exec foo expfactory users --list
/scif/data/expfactory/3eb83c14-ee01-4b38-a579-c927942732a8_finished	3eb83c14-ee01-4b38-a579-c927942732a8[finished]
```
and when I try to re-enter the subject id:

![image](https://user-images.githubusercontent.com/814322/33845079-1bd0d484-de57-11e7-90ab-f016eb87110e.png)


@earcanal let me know if this resolves the issue, and then let's summarize what is left to resolve before merging the PR.

**Comment by earcanal** [comment]
Might want to mention the cache gotcha in this message

    To build, cd to directory with Dockerfile and:
                  docker build -t expfactory/experiments .

**Comment by earcanal** [comment]
I'm blocked by "Confirm that there are no users" as there are, and I don't know how to delete them (see #48).

**Comment by vsoch** [comment]
@earcanal I just updated the entrypoint message so it shows the --no-cache, and I'm debugging #48 now.

**Comment by vsoch** [comment]
Also, if you are running a filesystem "database" - if you start a new container and map a previous folder, the application will find those previous folders as users. In my example above, the folder was empty. If you've run the container mapper to that folder before, likely it won't be (and you won't be able to confirm no users). If you want to do this, just delete the expfactory folder (it will be regenerated)

**Comment by earcanal** [comment]
Ah, that explains a lot, and unblocks.

**Comment by earcanal** [comment]
PASS.

**Comment by vsoch** [comment]
also there was a bug with finish! I just fixed it up:

```
$ docker exec foo expfactory users --finish 3eb83c14-ee01-4b38-a579-c927942732a8
[finishing] 3eb83c14-ee01-4b38-a579-c927942732a8 --> /scif/data/expfactory/3eb83c14-ee01-4b38-a579-c927942732a8_finished

$ docker exec foo expfactory users --restart 3eb83c14-ee01-4b38-a579-c927942732a8
[restarting] 3eb83c14-ee01-4b38-a579-c927942732a8 --> /scif/data/3eb83c14-ee01-4b38-a579-c927942732a8

$ docker exec foo expfactory users --finish 3eb83c14-ee01-4b38-a579-c927942732a8
[finishing] 3eb83c14-ee01-4b38-a579-c927942732a8 --> /scif/data/expfactory/3eb83c14-ee01-4b38-a579-c927942732a8_finished
```
