### ISSUE TITLE
[JOSS Review] Community guidelines

### ISSUE THREAD

**Issue by oesteban** [expfactory/expfactory#54]
As per openjournals/joss-reviews#521:

> **Community guidelines**: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I think the project would greatly benefit if:

  - Added the GitHub's magics for contributions (https://github.com/expfactory/expfactory/community)
  - The README was updated giving very brief (but present) pointers to how to communicate.

**Comment by vsoch** [comment]
Thanks @oesteban ! This is very good and sound advice, and I've added community guidelines (detailed in the README) to address the point. If you want to take a look --> https://github.com/expfactory/expfactory/pull/56 and please let me know if any language should be changed, or anything made better or more clear.
