### ISSUE TITLE
Number-Letter Task No Stimuli

### ISSUE THREAD

**Issue by theholyman619** [expfactory/expfactory#60]
The Number-Letter task stops showing any stimuli after a certain point. It still responds to user input, but there's nothing other than the 4 quadrants on the screen. This error occurs when it is being run as part of a battery, as well as on its own.

**Comment by vsoch** [comment]
Can you see any error in the console log that you could quickly show me? And could you please submit the bug on the repository for the task itself? --> https://github.com/expfactory-experiments/number-letter   This is for one the driver software :) Thank you!

**Comment by vsoch** [comment]
hey @theholyman619 I'm closing the issue here, if there is an issue with a paritcular experiment please open on the board in question, since this is for the core expfactory software. Thanks!
