### ISSUE TITLE
Error generating survey from survey.tsv + config.json

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#69]
## Version of Experiment Factory:

Not sure how to find this.

### Expected behavior

survey.tsv, config.json -> index.html ...

### Actual behavior

```
Unable to find image 'vanessa/expfactory-survey:latest' locally docker: Error response from daemon: pull access denied for vanessa/expfactory-survey, repository does not exist or may require 'docker login'. See 'docker run --help'.
```
### Steps to reproduce behavior

(See instructions: https://expfactory.github.io/expfactory/integrations.html#contribute-a-survey)

`$ docker run -v $PWD:/data vanessa/expfactory-survey start`

**Comment by vsoch** [comment]
This is because the container I built locally for the example I named differently than the one that was actually pushed, here https://hub.docker.com/r/vanessa/survey-generator/ you would need to build the container on your own to have it be named that!

**Comment by earcanal** [comment]
Errr, if you say so.  Can you update the instructions so I can cargo-cult cut and paste to generate a survey?

**Comment by vsoch** [comment]
done!
