### ISSUE TITLE
Can't simultaneously access > 1 container on the same host 

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#72]
As a researcher, I'd like to run n containers (one per condition of a study) on the same host, and access them using different ports.  This is especially useful with `--headless` as it allow you to specify the task order for each condition once at container start, e.g.

`docker run -p 81:81 -d --name study5-control -v /tmp/test/data:/scif/data expfactory/experiments --headless --no-randomize --experiments simple-demographics-survey-2, state-mindfulness-survey, attention-network-task-no-feedback, zoning-out-task, attention-network-task-no-practice, state-mindfulness-survey-2 start`

I don't think this is currently possible as `nginx` is configured to only listen on port 80.  The only workaround I can think of is to run a virtual host per condition, which requires additional cost and config effort.

**Comment by vsoch** [comment]
Defining another port for a single server for nginx is outside the scope of expfactory, this is a niche use case that I can't offer support for.

**Comment by earcanal** [comment]
So would you do this by running a single container on each virtual host?

**Comment by earcanal** [comment]
I think this was just a crossed wire, due to my inexperience with Docker.  I _can_ run multiple containers on different ports on the same vm configured for different conditions e.g.

`docker run -p 8080:80 -d --name foo -v /tmp/test/data:/scif/data expfactory/experiments --headless --no-randomize --experiments simple-demographics-survey-2,state-mindfulness-survey,attention-network-task-no-feedback,breath-counting-task,attention-network-task-no-practice,state-mindfulness-survey-2 start
`
