### ISSUE TITLE
POST fails with 413 (payload too large)

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#77]
## Version of Experiment Factory: 3.1.0

Remote returns 413 for ~1.1MB JSON payload at end of experiment.  This _might_ be resolved with [updated ngnix config](https://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/).

### Expected behavior

Payload saved by container.

### Actual behavior

Payload saved locally (follows `error:` path of `promise.then` in standard `index.html` experiment pattern).

### Steps to reproduce behavior

1. Build a container containing [rsvp task](https://github.com/earcanal/rsvp-task) which generates payloads > 1MB.
1. Run task.

**Comment by earcanal** [comment]
Adding `client_max_body_size 20M;` appears to resolve this issue.  I did this in `/etc/nginx/sites-available/default` in a running container.  I'm not sure if this is the best config file for the patch, or how to apply it so that it gets included when building containers.

**Comment by vsoch** [comment]
This is an experiment-specific setting that wouldn't make sense to change the server default to support. You can change this easily for your container! The default isn't going to be the perfect use case for every experiment. Some might argue that the payload for the experiment should not be so large.

**Comment by earcanal** [comment]
I was surprised at the size of the payload.  It's partly a factorial effect of this particular paradigm (20 stimuli per trial x (practice + test) ).  Current payloads are inflated by the extensive escape characters which are a side effect of #76, although I think payloads on this task will still be > 1MB when #76 is resolved.

How would you make changes to nginx config when _building_ the container?  (I expect this is a simple answer which exposes my very limited understanding of Docker!)  Currently I only know how to make the change in a running container, which means having to reconfigure and restart nginx each time I restart the container.  If it's possible to specify at container build time, could we add this to the docs?  Whilst this is an edge case, it's hard to debug when triggered.

**Comment by vsoch** [comment]
The payload coming from the server wouldn't yet be json dumped, so that's not an issue. If #78 solves you issue then feel free to close this. In the next go around a better solution would allow for saving partial data (multiple times during the experiment).
