### ISSUE TITLE
Invalid token on headless server

### ISSUE THREAD

**Issue by tylerburleigh** [expfactory/expfactory#80]
## Version of Experiment Factory:

3.12 (I think?)

### Expected behavior

I start a headless server
I generate tokens
I use a token to enter the portal

### Actual behavior

I start a headless server
I generate tokens
I try a token and it says it's invalid

### Steps to reproduce behavior

See above...

Console output:
```
root@docker-s-1vcpu-1gb-nyc1-01:/tmp/my-experiment# docker run -v /tmp/my-experiment/data/:/scif/data            -d -p 80:80            expfactory/experiments --headless --no-randomize start
c5783b9b352d9e9a36afa202ecdeeca618187c182663f0822ee504b9d205bd90
root@docker-s-1vcpu-1gb-nyc1-01:/tmp/my-experiment# docker exec c578 expfactory users --new 3
DATABASE        TOKEN
/scif/data/expfactory/fd0c2f82-cf7f-4726-a790-3f02f66780df      fd0c2f82-cf7f-4726-a790-3f02f66780df[active]
/scif/data/expfactory/d2a177b4-9acb-4525-85c6-8f7a56766d66      d2a177b4-9acb-4525-85c6-8f7a56766d66[active]
/scif/data/expfactory/15d4aade-09ad-4de9-a58f-31c35bdaf0df      15d4aade-09ad-4de9-a58f-31c35bdaf0df[active]
```

Attempting to use token:
![image](https://user-images.githubusercontent.com/3513754/41810119-f57a4fc8-76c6-11e8-9d0c-1358bce085d7.png)

**Comment by vsoch** [comment]
Following up on this issue! We debugged in gitter, and tested the following:

 - the session cookie was saving (and no errors in the browser)
 - it wasn't an issue of copy pasting from windows
 - the experiment did run without headless mode
 - note that this was running on some special Docker ready Droplet on Digital Ocean
 - built the same container but wasn't able to reproduce (I have ubuntu 16.04)

At the end of the day @tylerburleigh started another Droplet, just with a clean ubuntu install, and it worked without a hitch. I'm going to close the issue, hopefully this log will help others that might run into similar.
